# Generated by Django 5.2.3 on 2025-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillow', '0002_profiletype_alter_property_property_type_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedhistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
