# Generated by Django 5.2.5 on 2025-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillow', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.ManyToManyField(related_name='profiles', to='zillow.profiletype'),
        ),
    ]
