# Generated by Django 5.2.5 on 2025-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillow', '0003_profiletype_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.ManyToManyField(default='Buyer', related_name='profiles', to='zillow.profiletype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ManyToManyField(default='House', related_name='properties', to='zillow.propertytype'),
        ),
    ]
